name: CI
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8', '8.10', '9.0']
        cabal: ['3.2', '3.4']
        os: [ubuntu-latest]
        exclude:
          - ghc: 9.0
            cabal: 3.2

    name: ghc-${{ matrix.ghc }} cabal-${{matrix.cabal}} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-v1-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-v1-

      - name: Install zookeeper-dev on ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libzookeeper-mt-dev

      - name: Setup zookeeper server
        run: docker run --name some-zookeeper -p 2182:2181 -d zookeeper

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Build
        run: cabal build --upgrade-dependencies --enable-tests --enable-benchmarks

      - name: Test
        run: cabal test --test-show-details=always

      - name: Check
        run: |
          cabal check
          cabal haddock
